In [20]:
import os
import sys
import numpy as np
import matplotlib.pyplot as plt




In [2]:
alpha=0.05
# we like fractions better then percentages. as a rule of thumb, either use fractions or counts
P_0 = 3.5 * 0.01 
P_1 = 70.1 * 0.01

if P_0 - P_1 >= 0:
    # we are done
    print ("the Null holds")
else:
    print ("we must assess the statistical significance")

n_0 = 409
n_1 = 564

#lets get the counts by multiplying by the sample size
Nt_0 = P_0 * n_0
Nt_1 = P_1 * n_1

we must assess the statistical significance


In [3]:

#define the sample proportion first
sp = (P_0 * n_0 + P_1 * n_1) / (n_1 + n_0)
print (sp)

0.421047276465


In [4]:
p = lambda p0, p1, n0, n1: (p0 * n0 + p1 * n1) / (n0 + n1)
#standard error
se = lambda p, n0, n1: np.sqrt(p * (1 - p) * (1.0 / n0 + 1.0 / n1))

In [8]:
zscore = lambda p0, p1, s : (p0 - p1) / s
z_2y = zscore(P_1, P_0, se(p(P_0, P_1, n_0, n_1), n_0, n_1))
print (z_2y)

20.7697865408


In [9]:
p_2y = 1 - 0.9984


def report_result(p,a):
    print ('is the p value ' + 
           '{0:.2f} smaller than the critical value {1:.2f}?'.format(p,a))
    if p < a:
        print ("YES!")
    else: 
        print ("NO!")
    
    print ('the Null hypothesis is {}'.format(\
                            'rejected' if p < a  else 'not rejected') )

    
report_result(p_2y, alpha)

is the p value 0.00 smaller than the critical value 0.05?
YES!
the Null hypothesis is rejected


NULL HYPOTHESIS: the % of former prisoners convicted of a felony is the same or higher for candidates who participated in the program as for the control group, significance level p=0.05

In [41]:
p_1 = 10.0 * .01
p_0 = 11.7 * .01

if p_0 - p_1 <= 0:
    # we are done
    print ("the Null holds")
else:
    print ("we must assess the statistical significance")
    
n_0 = 409
n_1 = 568

Nt_0 = p_0 * n_0
Nt_1 = p_1 * n_1

we must assess the statistical significance


In [23]:
sp = (p_0 * n_0 + p_1 * n_1) / (n_1 + n_0)
print (sp)

0.107116683726


In [24]:
z = zscore(p_1, p_0, se(p(p_0, p_1, n_0, n_1), n_0, n_1))
print(z)

-0.84764020522


In [25]:
import scipy.stats

In [26]:
z = abs(z)
p_val = 1 - scipy.stats.norm.cdf(z)
report_result(p_val, alpha)

is the p value 0.20 smaller than the critical value 0.05?
NO!
the Null hypothesis is not rejected


In [27]:
print(p_val)

0.198319188134


###Chi-square

In [31]:
#Ntot = 973 # a + b + c + d = tot

s#ample_values = np.array([[0.701 * 564, 0.299 * 564], [0.0305 * 409, 0.965 * 409]])
#sample_values

array([[ 395.364 ,  168.636 ],
       [  12.4745,  394.685 ]])

In [32]:
from scipy.stats import chisquare

In [33]:
chisquare(sample_values, axis=None)

Power_divergenceResult(statistic=432.0400995189255, pvalue=2.5373959963556308e-93)

In [34]:
con_table = np.array([[p_1 * n_1, (1-p_1)*n_1], [p_0 * n_0, (1-p_0)* n_0]])

In [35]:
con_table

array([[  56.8  ,  511.2  ],
       [  47.853,  361.147]])

In [42]:
chisquare(con_table, axis=None)

Power_divergenceResult(statistic=649.48411552917082, pvalue=1.8845503190687889e-140)

In [43]:
scipy.stats.chi2_contingency(con_table, correction=False)

(0.71849391750528779,
 0.3966383762686172,
 1,
 array([[  60.84227636,  507.15772364],
        [  43.81072364,  365.18927636]]))